name: ğŸ—ï¸ Build and Push Latest

on:
  push:
    branches: [ main ]
  workflow_dispatch: ~
  schedule:
    # At 14:00 UTC every day
    - cron: '0 14 * * *'

jobs:
  build:
    uses: ./.github/workflows/build-push.yml
    with:
      stream: latest
      push: true
    secrets: inherit
